<script setup>
import { computed, reactive } from 'vue';
import { storeToRefs } from 'pinia';
import TiendaLayout from '../../components/TiendaLayout.vue';
import ProductoVisual from '../../components/ProductoVisual.vue';
import { useCarritoStore } from '../../stores/carrito';
const carrito=useCarritoStore(); const {items,cantidadItems,total}=storeToRefs(carrito);
const contacto=reactive({nombre:'',telefono:'',nota:''}); const numeroWhatsApp='59169078166';
const mensaje=computed(()=>[`Hola, quiero hacer este pedido:`,...items.value.map(i=>`• ${i.nombre} x${i.cantidad} - $${(i.precioUnitario*i.cantidad).toFixed(2)}`),`Total referencial: $${total.value.toFixed(2)}`,`Nombre: ${contacto.nombre}`,`Teléfono: ${contacto.telefono}`,contacto.nota&&`Nota: ${contacto.nota}`].filter(Boolean).join('\n'));
const enlace=computed(()=>`https://wa.me/${numeroWhatsApp}?text=${encodeURIComponent(mensaje.value)}`);
</script>
<template><TiendaLayout><main class="checkout"><p class="pasos mono"><b>01 SELECCIÓN</b><span></span>02 DATOS<span></span>03 WHATSAPP</p><h1>Tu selección de productos</h1><p class="aclaracion">Este carrito no procesa pagos. Úsalo para preparar tu pedido y consultar disponibilidad por WhatsApp.</p>
<div v-if="items.length" class="checkout-grid"><section><h2>Productos seleccionados <small>({{cantidadItems}})</small></h2><div class="items"><article v-for="item in items" :key="item.productoId"><div class="visual"><ProductoVisual :tipo="item.categoria"/></div><div class="item-info"><small>{{item.categoria}}</small><h3>{{item.nombre}}</h3><p>{{item.marca}}</p><button @click="carrito.quitarProducto(item.productoId)">Eliminar</button></div><div class="item-precio"><strong>${{item.precioUnitario.toFixed(2)}}</strong><div><button @click="carrito.cambiarCantidad(item.productoId,item.cantidad-1)">−</button><span>{{item.cantidad}}</span><button @click="carrito.cambiarCantidad(item.productoId,item.cantidad+1)">+</button></div></div></article></div><router-link to="/tienda" class="seguir">← Seguir seleccionando</router-link></section>
<aside><div class="resumen"><h2>Resumen referencial</h2><p><span>Productos</span><strong>{{cantidadItems}}</strong></p><p class="total"><span>Total estimado</span><strong>${{total.toFixed(2)}}</strong></p><small>El negocio confirmará stock, entrega y precio final por WhatsApp.</small></div><form @submit.prevent><h3>Datos de contacto</h3><label>Nombre<input v-model="contacto.nombre" required></label><label>Teléfono<input v-model="contacto.telefono" required></label><label>Nota opcional<textarea v-model="contacto.nota" rows="3"></textarea></label><a :class="['whatsapp',{disabled:!contacto.nombre||!contacto.telefono}]" :href="contacto.nombre&&contacto.telefono?enlace:null" target="_blank" rel="noopener"><span class="material-symbols-outlined">chat</span>Enviar pedido por WhatsApp</a></form></aside></div>
<section v-else class="vacio"><span class="material-symbols-outlined">shopping_bag</span><h2>Aún no seleccionaste productos</h2><p>Explora el catálogo y agrega lo que te interese.</p><router-link class="btn-primary" to="/tienda">Ver catálogo</router-link></section></main></TiendaLayout></template>
<style scoped>
.checkout{max-width:1280px;margin:auto;padding:45px clamp(20px,5vw,70px)}.pasos{display:flex;align-items:center;gap:12px;color:#626762;font-size:9px}.pasos b{color:#79dd68}.pasos span{height:1px;width:38px;background:#373737}.checkout>h1{font-size:42px;margin:20px 0 10px}.aclaracion{color:#9ba397;line-height:1.6;margin-bottom:40px}.checkout-grid{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(350px,.8fr);gap:60px}.checkout h2{font-size:20px;margin-bottom:19px}.items{border-top:1px solid #313131}.items article{display:grid;grid-template-columns:120px 1fr auto;gap:20px;padding:20px 0;border-bottom:1px solid #313131}.visual{height:115px;display:grid;place-items:center;background:#202020;border-radius:6px;padding:25px}.item-info small{color:#79dd68}.item-info h3{margin:7px 0}.item-info p{color:#888}.item-info button{border:0;background:transparent;color:#aaa;text-decoration:underline;padding-top:15px}.item-precio{text-align:right}.item-precio>div{display:flex;margin-top:30px}.item-precio button,.item-precio span{width:29px;height:29px;border:1px solid #353535;background:#1d1d1d;color:#fff}.seguir{display:inline-block;color:#79dd68;margin-top:22px}.resumen,form{background:#1a1a1a;padding:25px}.resumen p{display:flex;justify-content:space-between;color:#aaa;margin:13px 0}.resumen .total{border-top:1px solid #363636;padding-top:20px;font-size:20px}.resumen .total strong{color:#79dd68}.resumen small{color:#777}form{margin-top:2px}form h3{margin-bottom:18px}form label{display:flex;flex-direction:column;gap:7px;font-size:10px;color:#91998e;margin-bottom:13px;text-transform:uppercase}form input,form textarea{background:#101010;border:1px solid #303030;color:#eee;padding:12px}.whatsapp{display:flex;justify-content:center;gap:8px;background:#25d366;color:#061c0e;padding:15px;border-radius:6px;font-weight:900}.disabled{opacity:.4;pointer-events:none}.vacio{text-align:center;padding:80px 20px;background:#191919}.vacio>span{font-size:48px;color:#79dd68}.vacio h2{margin:16px}.vacio p{color:#888;margin-bottom:28px}@media(max-width:900px){.checkout-grid{grid-template-columns:1fr}}@media(max-width:550px){.items article{grid-template-columns:85px 1fr}.item-precio{grid-column:2;display:flex;justify-content:space-between}.item-precio>div{margin:0}}
</style>
