<script setup>
import TiendaLayout from '../../components/TiendaLayout.vue';
</script>

<template>
  <TiendaLayout :buscador="false">
    <main class="acceso">
      <section class="presentacion"><div class="reticula"></div><div class="marca"><span class="material-symbols-outlined">sports_esports</span></div><div class="copy"><p class="mono">TU UNIVERSO. UNA CUENTA.</p><h1>Vuelve al juego.</h1><p>Consulta tus pedidos, guarda tus favoritos y da seguimiento a tus equipos en servicio técnico.</p><div class="beneficio"><span class="material-symbols-outlined">bolt</span><div><b>Todo en un solo lugar</b><small>Compras, soporte y recompensas.</small></div></div></div></section>
      <section class="formulario"><div class="form-box"><p class="sobre">CUENTA X-STORE</p><h2>Iniciar sesión</h2><p class="intro">Ingresa tus datos para continuar.</p><form><label>Correo electrónico<div><span class="material-symbols-outlined">mail</span><input type="email" placeholder="nombre@ejemplo.com" /></div></label><label>Contraseña<div><span class="material-symbols-outlined">lock</span><input type="password" placeholder="••••••••" /><button type="button" aria-label="Mostrar contraseña"><span class="material-symbols-outlined">visibility</span></button></div></label><a href="#">¿Olvidaste tu contraseña?</a><button type="button" class="entrar">Iniciar sesión <span>→</span></button></form><div class="separador"><span></span>O CONTINÚA CON<span></span></div><button class="social"><b>G</b>Google</button><p class="registro">¿No tienes cuenta? <a href="#">Crear una cuenta</a></p></div></section>
    </main>
  </TiendaLayout>
</template>

<style scoped>
.acceso{min-height:calc(100vh - 82px);display:grid;grid-template-columns:1.05fr .95fr}.presentacion{position:relative;overflow:hidden;padding:70px clamp(35px,7vw,110px);display:flex;flex-direction:column;justify-content:space-between;background:radial-gradient(circle at 25% 30%,#1e4a20,#101010 62%)}.reticula{position:absolute;inset:0;background:linear-gradient(#ffffff05 1px,transparent 1px),linear-gradient(90deg,#ffffff05 1px,transparent 1px);background-size:55px 55px;transform:perspective(500px) rotateX(57deg) scale(1.6);transform-origin:bottom;opacity:.6}.marca,.copy{z-index:1}.marca{width:54px;height:54px;border:1px solid #79dd68;display:grid;place-items:center;color:#79dd68}.copy{max-width:590px}.copy>p:first-child,.sobre{font-size:10px;color:#79dd68;letter-spacing:.16em;font-weight:800}.copy h1{font-size:clamp(52px,7vw,92px);letter-spacing:-.07em;line-height:.9;margin:15px 0 25px}.copy>p:nth-child(3){color:#afb7ac;line-height:1.7;max-width:500px}.beneficio{display:flex;align-items:center;gap:13px;margin-top:35px}.beneficio>span{width:42px;height:42px;display:grid;place-items:center;background:#79dd68;color:#062d08}.beneficio small{display:block;color:#899087;margin-top:5px}.formulario{display:grid;place-items:center;padding:40px;background:#151515}.form-box{width:min(430px,100%)}.form-box h2{font-size:34px;margin:11px 0}.intro{color:#929a90;margin-bottom:28px}.form-box label{display:block;font-size:11px;color:#bec6bb;text-transform:uppercase;letter-spacing:.06em;font-weight:800;margin-bottom:16px}.form-box label div{display:flex;align-items:center;background:#0f0f0f;border:1px solid #303030;border-radius:6px;margin-top:8px;padding:0 13px}.form-box label div:focus-within{border-color:#79dd68}.form-box input{width:100%;padding:14px 11px;background:transparent;border:0;color:#fff;outline:0}.form-box label button{border:0;background:transparent;color:#888}.form-box form>a{float:right;color:#79dd68;font-size:11px;margin-top:-5px}.entrar{width:100%;display:flex;justify-content:space-between;border:0;background:#107c10;color:#fff;padding:15px 18px;border-radius:6px;font-weight:900;margin-top:33px}.separador{display:flex;align-items:center;gap:10px;color:#686868;font-size:9px;margin:25px 0}.separador span{height:1px;background:#333;flex:1}.social{width:100%;padding:13px;border:1px solid #373737;background:#202020;color:#fff;border-radius:6px}.social b{margin-right:10px}.registro{text-align:center;color:#858585;font-size:12px;margin-top:25px}.registro a{color:#79dd68;font-weight:700}
@media(max-width:850px){.acceso{grid-template-columns:1fr}.presentacion{min-height:410px}.formulario{padding:65px 25px}}@media(max-width:500px){.presentacion{padding:45px 25px}.copy h1{font-size:50px}}
</style>
