<script setup>
import { reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import TiendaLayout from '../../components/TiendaLayout.vue';
import { consultarServicioPublicoApi } from '../../services/recursosApi';
const router=useRouter(),error=ref(''),consultando=ref(false),form=reactive({id:'',verificacion:''});
async function consultar(){consultando.value=true;error.value='';try{await consultarServicioPublicoApi(form.id,form.verificacion);sessionStorage.setItem(`consulta-servicio-${form.id}`,form.verificacion);router.push(`/tienda/servicio/${form.id}`)}catch(e){error.value=e.response?.data?.message||'No se encontró una orden con esos datos.'}finally{consultando.value=false}}
</script>
<template><TiendaLayout :buscador="false"><main class="consulta"><section><p class="eyebrow mono">SOPORTE / TALLER</p><h1>Consulta tu reparación</h1><p>Ingresa el número de orden y confirma el CI o teléfono registrado al recibir el equipo.</p><a class="soporte" href="https://wa.me/59169078166?text=Hola%2C%20necesito%20ayuda%20con%20un%20servicio%20t%C3%A9cnico" target="_blank" rel="noopener"><span class="material-symbols-outlined">chat</span>Contactar soporte por WhatsApp</a></section><form @submit.prevent="consultar"><div class="campo"><label>Número de orden</label><div class="prefijo"><span>#SRV-</span><input v-solo-digitos v-model.trim="form.id" inputmode="numeric" pattern="[0-9]+" required maxlength="10" placeholder="0001"></div></div><div class="campo"><label>CI o teléfono</label><input v-model.trim="form.verificacion" required minlength="4" maxlength="20" pattern="[A-Za-z0-9-]+" title="Usa el CI o teléfono sin espacios." autocomplete="off"></div><p v-if="error" class="error" role="alert">{{error}}</p><button class="btn-primary" :disabled="consultando">{{consultando?'Consultando...':'Ver estado del servicio'}}</button></form></main></TiendaLayout></template>
<style scoped>.consulta{min-height:65vh;max-width:900px;margin:auto;padding:80px 24px;display:grid;grid-template-columns:1.2fr .8fr;gap:70px;align-items:center}.eyebrow{color:#79dd68;font-size:11px}.consulta h1{font-size:clamp(38px,6vw,64px);line-height:1;margin:12px 0}.consulta section>p:last-of-type{color:#9ba497;line-height:1.7}.soporte{display:inline-flex;align-items:center;gap:8px;margin-top:22px;color:#79dd68;font-weight:700}.consulta form{display:grid;gap:18px;padding:28px;background:#191919;border:1px solid #303030;border-radius:12px}.prefijo{display:flex;align-items:center;background:#101010;border:1px solid #383838;border-radius:7px}.prefijo span{padding-left:12px;color:#79dd68}.prefijo input{border:0}.error{color:#ffb4ab;font-size:13px}@media(max-width:750px){.consulta{grid-template-columns:1fr;gap:30px}}</style>
