<script setup>
import { computed, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import TiendaLayout from '../../components/TiendaLayout.vue';
import { consultarServicioPublicoApi } from '../../services/recursosApi';
const props=defineProps({id:{type:String,required:true}}),router=useRouter(),servicio=ref(null),error=ref('');
const etapas=['Recibido','En diagnóstico','En reparación','En pruebas','Listo para entrega','Entregado'];
const indice=computed(()=>Math.max(0,etapas.indexOf(servicio.value?.estado)));
const total=computed(()=>Number(servicio.value?.costoManoObra||0)+(servicio.value?.detalles||[]).reduce((s,d)=>s+Number(d.subtotal),0));
onMounted(async()=>{const validacion=sessionStorage.getItem(`consulta-servicio-${props.id}`);if(!validacion){router.replace('/tienda/servicio');return}try{servicio.value=await consultarServicioPublicoApi(props.id,validacion)}catch(e){error.value=e.response?.data?.message||'No se pudo consultar la orden.'}});
</script>
<template><TiendaLayout :buscador="false"><main class="seguimiento"><p v-if="error" class="error">{{error}}</p><div v-else-if="servicio"><router-link class="volver" to="/tienda/servicio">← Consultar otra orden</router-link><header><p class="eyebrow mono">ORDEN #SRV-{{String(servicio.id).padStart(4,'0')}}</p><h1>Seguimiento de reparación</h1><span class="estado">{{servicio.estado}}</span></header><section class="resumen"><article><small>DISPOSITIVO</small><strong>{{servicio.dispositivo}}</strong></article><article><small>INGRESO</small><strong>{{new Date(servicio.fechaIngreso).toLocaleDateString('es-BO')}}</strong></article><article><small>TÉCNICO</small><strong>{{servicio.empleado||'Por asignar'}}</strong></article><article><small>TOTAL ESTIMADO</small><strong>${{total.toFixed(2)}}</strong></article></section><section class="panel"><h2>Progreso</h2><div class="pasos"><article v-for="(etapa,i) in etapas" :key="etapa" :class="{completo:i<=indice,actual:i===indice}"><i><span class="material-symbols-outlined">{{i<indice?'check':i===indice?'handyman':'radio_button_unchecked'}}</span></i><b>{{etapa}}</b></article></div></section><section class="panel"><h2>Diagnóstico</h2><p>{{servicio.diagnostico||'El equipo está pendiente de diagnóstico técnico.'}}</p></section></div><p v-else>Cargando seguimiento...</p></main></TiendaLayout></template>
<style scoped>.seguimiento{max-width:1100px;margin:auto;padding:55px 24px;min-height:65vh}.volver,.eyebrow{color:#79dd68}.volver{font-size:13px}header{margin:25px 0}header h1{font-size:clamp(35px,5vw,52px);margin:8px 0}.estado{display:inline-block;padding:8px 12px;background:#173919;color:#79dd68;border-radius:6px}.resumen{display:grid;grid-template-columns:repeat(4,1fr);background:#191919;border-left:4px solid #79dd68}.resumen article{padding:20px;border-right:1px solid #333}.resumen small{display:block;color:#899287;font-size:9px;margin-bottom:7px}.panel{margin-top:20px;padding:26px;background:#191919;border-radius:8px}.panel h2{margin-bottom:20px}.panel>p{color:#b0b7ad;line-height:1.7}.pasos{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.pasos article{display:grid;justify-items:center;text-align:center;gap:8px;color:#666}.pasos i{width:39px;height:39px;display:grid;place-items:center;border-radius:50%;background:#303030}.pasos b{font-size:11px}.pasos .completo{color:#fff}.pasos .completo i{background:#107c10}.pasos .actual i{box-shadow:0 0 0 5px #79dd6825}.error{color:#ffb4ab}@media(max-width:750px){.resumen{grid-template-columns:1fr 1fr}.pasos{grid-template-columns:repeat(3,1fr)}}</style>
