<script setup>
import { computed, onMounted, ref } from 'vue';
import AdminLayout from '../../components/AdminLayout.vue';
import { clientesApi, dispositivosApi, serviciosApi, ventasApi } from '../../services/recursosApi';
const props=defineProps({id:{type:String,required:true}});
const cliente=ref(null),ventas=ref([]),servicios=ref([]),dispositivos=ref([]),error=ref('');
const id=computed(()=>Number(props.id));
onMounted(async()=>{try{const r=await Promise.all([clientesApi.obtenerPorId(id.value),ventasApi.obtenerTodos(),serviciosApi.obtenerTodos(),dispositivosApi.obtenerTodos()]);cliente.value=r[0];ventas.value=r[1].filter(x=>x.clienteId===id.value);servicios.value=r[2].filter(x=>x.clienteId===id.value);dispositivos.value=r[3].filter(x=>x.clienteId===id.value)}catch{error.value='No se encontró la ficha del cliente.'}});
</script>
<template><AdminLayout titulo="Ficha del cliente"><p v-if="error" class="error">{{error}}</p><div v-else-if="cliente" class="shell"><section class="panel-caso cabecera"><div><p class="eyebrow mono">CLIENTE #{{cliente.id}}</p><h2>{{cliente.nombre}} {{cliente.apellido}}</h2><p>CI {{cliente.ci||'no registrado'}} · {{cliente.telefono}} · {{cliente.email||'sin correo'}}</p><small>{{cliente.direccion||'Sin dirección'}} · Registro {{new Date(cliente.fechaRegistro).toLocaleDateString('es-BO')}}</small></div><router-link class="btn-secondary" :to="`/admin/clientes/${cliente.id}/editar`">Editar ficha</router-link></section><div class="resumen-casos"><article><small>VENTAS</small><strong>{{ventas.length}}</strong></article><article><small>SERVICIOS</small><strong>{{servicios.length}}</strong></article><article><small>DISPOSITIVOS</small><strong>{{dispositivos.length}}</strong></article></div><section class="panel-caso"><h3>Dispositivos registrados</h3><div class="items"><article v-for="d in dispositivos" :key="d.id"><b>{{d.marca}} {{d.modelo}}</b><span>{{d.tipo}} · {{d.numeroSerie||'sin serie'}}</span></article><p v-if="!dispositivos.length" class="muted">Sin dispositivos.</p></div></section><section class="panel-caso"><h3>Historial comercial y técnico</h3><div class="items"><router-link v-for="v in ventas" :key="`v${v.id}`" :to="`/admin/ventas/${v.id}`">Venta #{{v.id}} · ${{Number(v.total).toFixed(2)}} · {{v.estado}}</router-link><router-link v-for="s in servicios" :key="`s${s.id}`" :to="`/admin/servicios/${s.id}`">Servicio #{{s.id}} · {{s.dispositivo}} · {{s.estado}}</router-link><p v-if="!ventas.length&&!servicios.length" class="muted">Sin actividad registrada.</p></div></section></div><p v-else>Cargando...</p></AdminLayout></template>
<style scoped>.shell{display:grid;gap:20px}.cabecera{display:flex;justify-content:space-between;align-items:center}.cabecera h2{font-size:30px;margin:7px 0}.cabecera p,.cabecera small,.muted{color:#929a90}.items{display:grid;gap:9px;margin-top:14px}.items article,.items a{display:flex;justify-content:space-between;padding:12px;background:#171717;border:1px solid #303030;border-radius:7px}.items a{color:#79dd68}.error{color:#ffb4ab}</style>
