<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import AdminLayout from '../../components/AdminLayout.vue';
import { clientesApi, dispositivosApi } from '../../services/recursosApi';
const clientes=ref([]),dispositivos=ref([]),editando=ref(null),error=ref('');
const form=reactive({clienteId:'',tipo:'Consola',marca:'',modelo:'',numeroSerie:'',observaciones:''});
const clienteSeleccionado=computed(()=>clientes.value.find(c=>c.id===Number(form.clienteId)));
async function cargar(){try{[clientes.value,dispositivos.value]=await Promise.all([clientesApi.obtenerTodos(),dispositivosApi.obtenerTodos()])}catch{error.value='No se pudieron cargar los dispositivos.'}}
function limpiar(){editando.value=null;Object.assign(form,{clienteId:'',tipo:'Consola',marca:'',modelo:'',numeroSerie:'',observaciones:''})}
function editar(d){editando.value=d.id;Object.assign(form,d)}
async function guardar(){error.value='';try{const payload={...form,clienteId:Number(form.clienteId),cliente:clienteSeleccionado.value?`${clienteSeleccionado.value.nombre} ${clienteSeleccionado.value.apellido}`:''};if(editando.value)await dispositivosApi.actualizar(editando.value,{...payload,id:editando.value});else await dispositivosApi.crear(payload);limpiar();await cargar()}catch{error.value='No se pudo guardar el dispositivo.'}}
onMounted(cargar);
</script>
<template><AdminLayout titulo="Dispositivos"><template #header><div class="modulo-header"><div><p class="eyebrow mono">TALLER / EQUIPOS</p><h2>Dispositivos de clientes</h2><p>Registra cada equipo una sola vez y consulta sus órdenes posteriores.</p></div><router-link class="btn-primary" to="/admin/servicios/nuevo">Nueva orden</router-link></div></template>
<form class="panel-caso formulario-grid" @submit.prevent="guardar"><div class="campo ancho"><label>Propietario</label><select v-model="form.clienteId" required><option value="">Seleccionar cliente</option><option v-for="c in clientes" :key="c.id" :value="c.id">{{c.nombre}} {{c.apellido}}</option></select></div><div class="campo"><label>Tipo</label><select v-model="form.tipo"><option>Consola</option><option>Control</option><option>Computadora</option><option>Accesorio</option><option>Otro</option></select></div><div class="campo"><label>Marca</label><input v-model.trim="form.marca" required></div><div class="campo"><label>Modelo</label><input v-model.trim="form.modelo" required></div><div class="campo"><label>Número de serie</label><input v-model.trim="form.numeroSerie"></div><div class="campo ancho"><label>Observaciones de recepción</label><textarea v-model.trim="form.observaciones" rows="3"></textarea></div><div class="acciones ancho"><button class="btn-primary">{{editando?'Actualizar':'Registrar dispositivo'}}</button><button v-if="editando" class="btn-secondary" type="button" @click="limpiar">Cancelar</button></div><p v-if="error" class="error ancho">{{error}}</p></form>
<section class="panel-caso"><table class="tabla-caso"><thead><tr><th>Equipo</th><th>Cliente</th><th>Serie</th><th>Observaciones</th><th></th></tr></thead><tbody><tr v-for="d in dispositivos" :key="d.id"><td><strong>{{d.marca}} {{d.modelo}}</strong><small>{{d.tipo}}</small></td><td>{{d.cliente}}</td><td class="mono">{{d.numeroSerie||'—'}}</td><td>{{d.observaciones||'—'}}</td><td><button class="accion-caso boton" @click="editar(d)">Editar</button></td></tr></tbody></table></section></AdminLayout></template>
<style scoped>.ancho{grid-column:1/-1}.acciones{display:flex;gap:10px}.boton{background:none;border:0;cursor:pointer}.tabla-caso small{display:block;color:#929a90;margin-top:4px}.error{color:#ffb4ab}@media(max-width:650px){.ancho{grid-column:auto}}</style>
