<script setup>
import { onMounted, reactive, ref } from 'vue';
import AdminLayout from '../../components/AdminLayout.vue';
import { empleadosApi, rolesApi, usuariosApi } from '../../services/recursosApi';
const empleados=ref([]),usuarios=ref([]),roles=ref([]),abierto=ref(false),guardando=ref(false),error=ref('');
const form=reactive({nombre:'',apellido:'',ci:'',telefono:'',email:'',direccion:'',cargo:'',salario:0,username:'',password:'',rolId:''});
async function cargar(){try{[empleados.value,usuarios.value,roles.value]=await Promise.all([empleadosApi.obtenerTodos(),usuariosApi.obtenerTodos(),rolesApi.obtenerTodos()])}catch{error.value='No se pudo cargar el personal.'}}
function usuarioDe(id){return usuarios.value.find(u=>u.empleadoId===id)}
async function guardar(){guardando.value=true;error.value='';try{const empleado=await empleadosApi.crear({nombre:form.nombre,apellido:form.apellido,ci:form.ci,telefono:form.telefono,email:form.email,direccion:form.direccion,cargo:form.cargo,salario:Number(form.salario),fechaIngreso:new Date().toISOString(),activo:true});const rol=roles.value.find(r=>r.id===Number(form.rolId));await usuariosApi.crear({empleadoId:empleado.id,rolId:rol.id,username:form.username,password:form.password,nombre:`${form.nombre} ${form.apellido}`,rol:rol.nombre,activo:true});abierto.value=false;Object.assign(form,{nombre:'',apellido:'',ci:'',telefono:'',email:'',direccion:'',cargo:'',salario:0,username:'',password:'',rolId:''});await cargar()}catch(e){error.value=e.response?.data?.message||'No se pudo crear el empleado y su usuario.'}finally{guardando.value=false}}
async function cambiarEstado(e){error.value='';try{const activo=!e.activo;await empleadosApi.actualizar(e.id,{...e,activo});const u=usuarioDe(e.id);if(u)await usuariosApi.actualizar(u.id,{...u,password:'',activo});await cargar()}catch{error.value='No se pudo cambiar el estado.'}}
onMounted(cargar);
</script>
<template><AdminLayout titulo="Personal"><template #header><div class="modulo-header"><div><p class="eyebrow mono">CONFIGURACIÓN / EQUIPO</p><h2>Personal del negocio</h2><p>Empleados, credenciales y roles persistidos en Firestore.</p></div><button class="btn-primary" @click="abierto=!abierto">Nuevo empleado</button></div></template>
<form v-if="abierto" class="panel-caso formulario-grid" @submit.prevent="guardar"><div class="campo"><label>Nombre</label><input v-model.trim="form.nombre" required></div><div class="campo"><label>Apellido</label><input v-model.trim="form.apellido" required></div><div class="campo"><label>CI</label><input v-model.trim="form.ci"></div><div class="campo"><label>Teléfono</label><input v-model.trim="form.telefono"></div><div class="campo"><label>Correo</label><input v-model.trim="form.email" type="email"></div><div class="campo"><label>Cargo</label><input v-model.trim="form.cargo" required></div><div class="campo"><label>Salario</label><input v-model.number="form.salario" type="number" min="0" required></div><div class="campo"><label>Rol de acceso</label><select v-model="form.rolId" required><option value="">Seleccionar</option><option v-for="r in roles" :key="r.id" :value="r.id">{{r.nombre}}</option></select></div><div class="campo"><label>Usuario</label><input v-model.trim="form.username" required></div><div class="campo"><label>Contraseña inicial</label><input v-model="form.password" type="password" minlength="6" required></div><button class="btn-primary" :disabled="guardando">{{guardando?'Creando...':'Crear empleado y acceso'}}</button></form>
<p v-if="error" class="error">{{error}}</p><section class="panel-caso"><table class="tabla-caso"><thead><tr><th>Empleado</th><th>Usuario</th><th>Rol</th><th>Cargo</th><th>Salario</th><th>Estado</th><th></th></tr></thead><tbody><tr v-for="e in empleados" :key="e.id"><td>{{e.nombre}} {{e.apellido}}</td><td class="mono">{{usuarioDe(e.id)?.username||'Sin acceso'}}</td><td>{{usuarioDe(e.id)?.rol||'—'}}</td><td>{{e.cargo}}</td><td>Bs {{Number(e.salario).toFixed(2)}}</td><td><span class="estado-caso">{{e.activo?'Activo':'Inactivo'}}</span></td><td><button class="accion-caso boton" @click="cambiarEstado(e)">{{e.activo?'Desactivar':'Activar'}}</button></td></tr></tbody></table></section></AdminLayout></template>
<style scoped>.boton{background:none;border:0;cursor:pointer}.error{color:#ffb4ab}</style>
