<script setup>
import { computed, onMounted, ref } from 'vue';
import AdminLayout from '../../components/AdminLayout.vue';
import { comprasApi, productosApi, serviciosApi, ventasApi } from '../../services/recursosApi';
const ventas=ref([]),compras=ref([]),productos=ref([]),servicios=ref([]),desde=ref('2026-01-01'),hasta=ref('2026-12-31'),error=ref('');
const enRango=fecha=>{const d=new Date(fecha);return d>=new Date(`${desde.value}T00:00:00`)&&d<=new Date(`${hasta.value}T23:59:59`)};
const vf=computed(()=>ventas.value.filter(v=>enRango(v.fecha))),cf=computed(()=>compras.value.filter(c=>enRango(c.fecha))),sf=computed(()=>servicios.value.filter(s=>enRango(s.fechaIngreso)));
const cobradoVentas=computed(()=>vf.value.flatMap(v=>v.pagos||[]).reduce((s,p)=>s+Number(p.monto),0));
const cobradoServicios=computed(()=>sf.value.flatMap(v=>v.pagos||[]).reduce((s,p)=>s+Number(p.monto),0));
const saldos=computed(()=>vf.value.reduce((s,v)=>s+Math.max(0,Number(v.total)-(v.pagos||[]).reduce((a,p)=>a+Number(p.monto),0)),0)+sf.value.reduce((s,v)=>s+Math.max(0,Number(v.total)-(v.pagos||[]).reduce((a,p)=>a+Number(p.monto),0)),0));
const gastos=computed(()=>cf.value.reduce((s,c)=>s+Number(c.total),0));
function agrupar(lista,clave,valor){const mapa={};for(const x of lista){const k=clave(x)||'Sin asignar';mapa[k]=(mapa[k]||0)+valor(x)}return Object.entries(mapa).sort((a,b)=>b[1]-a[1])}
const porEmpleado=computed(()=>agrupar(vf.value,v=>v.empleado,v=>Number(v.total)));
const porProducto=computed(()=>agrupar(vf.value.flatMap(v=>v.detalles||[]),d=>d.producto,d=>Number(d.cantidad)));
const metodos=computed(()=>agrupar([...vf.value,...sf.value].flatMap(x=>x.pagos||[]),p=>p.metodoPago,p=>Number(p.monto)));
const porEstado=computed(()=>agrupar(sf.value,s=>s.estado,()=>1));
const stockBajo=computed(()=>productos.value.filter(p=>p.activo&&p.stock<=p.stockMinimo));
onMounted(async()=>{try{[ventas.value,compras.value,productos.value,servicios.value]=await Promise.all([ventasApi.obtenerTodos(),comprasApi.obtenerTodos(),productosApi.obtenerTodos(),serviciosApi.obtenerTodos()])}catch{error.value='No se pudieron cargar todos los datos del reporte.'}});
</script>
<template><AdminLayout titulo="Reportes"><template #header><div class="modulo-header"><div><p class="eyebrow mono">ANÁLISIS / NEGOCIO</p><h2>Reporte integral</h2><p>Ingresos cobrados, saldos, compras, ventas, inventario y taller.</p></div><button class="btn-secondary" @click="window.print()">Imprimir / PDF</button></div></template><section class="panel-caso filtros"><div class="campo"><label>Desde</label><input v-model="desde" type="date"></div><div class="campo"><label>Hasta</label><input v-model="hasta" type="date"></div></section><p v-if="error" class="error">{{error}}</p><section class="metricas"><article><small>COBRADO EN VENTAS</small><strong>${{cobradoVentas.toFixed(2)}}</strong></article><article><small>COBRADO EN SERVICIOS</small><strong>${{cobradoServicios.toFixed(2)}}</strong></article><article><small>SALDOS PENDIENTES</small><strong>${{saldos.toFixed(2)}}</strong></article><article><small>COMPRAS / GASTOS</small><strong>${{gastos.toFixed(2)}}</strong></article><article><small>FLUJO NETO</small><strong>${{(cobradoVentas+cobradoServicios-gastos).toFixed(2)}}</strong></article></section><div class="tableros"><section class="panel-caso"><h3>Ventas por empleado</h3><p v-for="[k,v] in porEmpleado" :key="k"><span>{{k}}</span><b>${{v.toFixed(2)}}</b></p></section><section class="panel-caso"><h3>Productos vendidos</h3><p v-for="[k,v] in porProducto" :key="k"><span>{{k}}</span><b>{{v}} uds.</b></p></section><section class="panel-caso"><h3>Métodos de pago</h3><p v-for="[k,v] in metodos" :key="k"><span>{{k}}</span><b>${{v.toFixed(2)}}</b></p></section><section class="panel-caso"><h3>Servicios por estado</h3><p v-for="[k,v] in porEstado" :key="k"><span>{{k}}</span><b>{{v}}</b></p></section></div><section class="panel-caso"><h3>Productos bajo stock mínimo</h3><table class="tabla-caso"><thead><tr><th>Producto</th><th>Categoría</th><th>Stock</th><th>Mínimo</th><th>Margen unitario</th></tr></thead><tbody><tr v-for="p in stockBajo" :key="p.id"><td>{{p.nombre}}</td><td>{{p.categoria}}</td><td>{{p.stock}}</td><td>{{p.stockMinimo}}</td><td>${{(p.precioVenta-p.precioCompra).toFixed(2)}}</td></tr></tbody></table></section></AdminLayout></template>
<style scoped>.filtros{display:grid;grid-template-columns:1fr 1fr;gap:16px;max-width:600px}.metricas{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.metricas article{padding:18px;background:#1b1b1b;border:1px solid #303030;border-radius:8px}.metricas small{display:block;color:#929a90;font-size:10px}.metricas strong{display:block;color:#79dd68;font-size:22px;margin-top:7px}.tableros{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.tableros h3,.panel-caso>h3{margin-bottom:14px}.tableros p{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #303030}.error{color:#ffb4ab}@media(max-width:950px){.metricas{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.filtros,.tableros,.metricas{grid-template-columns:1fr}}@media print{button,.filtros{display:none}}
</style>
