<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import AdminLayout from '../../components/AdminLayout.vue';
import { actualizarSeguimientoServicioApi, productosApi, registrarPagoServicioApi, serviciosApi } from '../../services/recursosApi';
const props=defineProps({id:{type:String,required:true}});
const servicio=ref(null),productos=ref([]),error=ref(''),mensaje=ref(''),guardando=ref(false);
const estados=['Recibido','En diagnóstico','En reparación','En pruebas','Listo para entrega','Entregado','Cancelado'];
const seguimiento=reactive({estado:'Recibido',diagnostico:'',costoManoObra:0,detalles:[]});
const pago=reactive({metodoPago:'Efectivo',monto:0,referencia:''});
const total=computed(()=>Number(seguimiento.costoManoObra||0)+seguimiento.detalles.reduce((s,d)=>s+Number(d.cantidad||0)*Number(d.precioUnitario||0),0));
const pagado=computed(()=>servicio.value?.pagos?.reduce((s,p)=>s+Number(p.monto),0)||0);
const saldo=computed(()=>Math.max(0,total.value-pagado.value));
function agregarRepuesto(){seguimiento.detalles.push({productoId:'',cantidad:1,precioUnitario:0})}
function elegirProducto(linea){const p=productos.value.find(p=>p.id===Number(linea.productoId));if(p)linea.precioUnitario=p.precioVenta}
async function cargar(){try{[servicio.value,productos.value]=await Promise.all([serviciosApi.obtenerPorId(props.id),productosApi.obtenerTodos()]);Object.assign(seguimiento,{estado:servicio.value.estado,diagnostico:servicio.value.diagnostico,costoManoObra:servicio.value.costoManoObra,detalles:servicio.value.detalles?.map(d=>({...d}))||[]});pago.monto=Number(saldo.value.toFixed(2))}catch{error.value='No se pudo cargar la orden.'}}
async function guardar(){guardando.value=true;error.value='';mensaje.value='';try{servicio.value=await actualizarSeguimientoServicioApi(props.id,{...seguimiento,detalles:seguimiento.detalles.map(d=>({...d,productoId:Number(d.productoId)}))});mensaje.value='Seguimiento actualizado y stock sincronizado.';await cargar()}catch(e){error.value=e.response?.data?.message||'No se pudo actualizar el servicio.'}finally{guardando.value=false}}
async function registrarPago(){error.value='';mensaje.value='';try{servicio.value=await registrarPagoServicioApi(props.id,{...pago});mensaje.value='Pago de servicio registrado.';pago.referencia='';pago.monto=Number(saldo.value.toFixed(2))}catch(e){error.value=e.response?.data?.message||'No se pudo registrar el pago.'}}
onMounted(cargar);
</script>
<template><AdminLayout titulo="Detalle de servicio"><p v-if="!servicio&&!error">Cargando orden...</p><p v-if="error" class="error">{{error}}</p><div v-if="servicio" class="shell">
<header class="panel-caso cabecera"><div><router-link to="/admin/servicios" class="accion-caso">← Volver</router-link><p class="eyebrow mono">ORDEN #SRV-{{String(servicio.id).padStart(4,'0')}}</p><h2>{{servicio.dispositivo}}</h2><p>{{servicio.cliente}} · {{new Date(servicio.fechaIngreso).toLocaleString('es-BO')}}</p></div><span class="estado-caso">{{servicio.estado}}</span></header>
<div class="columnas"><form class="panel-caso formulario-caso" @submit.prevent="guardar"><h3>Seguimiento técnico</h3><div class="campo"><label>Estado actual</label><select v-model="seguimiento.estado"><option v-for="e in estados" :key="e">{{e}}</option></select></div><div class="campo"><label>Diagnóstico y trabajo realizado</label><textarea v-model.trim="seguimiento.diagnostico" rows="5" required></textarea></div><div class="campo"><label>Costo de mano de obra</label><input v-model.number="seguimiento.costoManoObra" type="number" min="0" step=".01"></div><h3>Repuestos utilizados</h3><article v-for="(d,i) in seguimiento.detalles" :key="i" class="repuesto"><select v-model="d.productoId" required @change="elegirProducto(d)"><option value="">Producto</option><option v-for="p in productos" :key="p.id" :value="p.id">{{p.nombre}} · stock {{p.stock}}</option></select><input v-model.number="d.cantidad" type="number" min="1" required aria-label="Cantidad"><input v-model.number="d.precioUnitario" type="number" min=".01" step=".01" required aria-label="Precio"><button type="button" aria-label="Quitar repuesto" @click="seguimiento.detalles.splice(i,1)">×</button></article><button class="accion-caso agregar" type="button" @click="agregarRepuesto">+ Agregar repuesto</button><button class="btn-primary" :disabled="guardando">{{guardando?'Guardando...':'Actualizar servicio'}}</button></form>
<aside><section class="panel-caso resumen"><h3>Costos y pagos</h3><p><span>Mano de obra</span><b>${{Number(seguimiento.costoManoObra||0).toFixed(2)}}</b></p><p><span>Repuestos</span><b>${{(total-Number(seguimiento.costoManoObra||0)).toFixed(2)}}</b></p><p class="total"><span>Total</span><b>${{total.toFixed(2)}}</b></p><p><span>Pagado</span><b>${{pagado.toFixed(2)}}</b></p><p class="saldo"><span>Saldo</span><b>${{saldo.toFixed(2)}}</b></p></section>
<form v-if="saldo>0" class="panel-caso formulario-caso" @submit.prevent="registrarPago"><h3>Registrar pago</h3><div class="campo"><label>Medio</label><select v-model="pago.metodoPago"><option>Efectivo</option><option>QR</option><option>Tarjeta</option></select></div><div class="campo"><label>Monto</label><input v-model.number="pago.monto" type="number" min=".01" :max="saldo" step=".01" required></div><div class="campo"><label>Referencia</label><input v-model.trim="pago.referencia"></div><button class="btn-primary">Registrar abono</button></form>
<section class="panel-caso"><h3>Historial de pagos</h3><p v-if="!servicio.pagos?.length" class="muted">Sin pagos registrados.</p><article v-for="p in servicio.pagos" :key="p.id" class="pago"><div><b>{{p.metodoPago}}</b><small>{{new Date(p.fecha).toLocaleString('es-BO')}}</small></div><strong>${{Number(p.monto).toFixed(2)}}</strong></article></section></aside></div><p v-if="mensaje" class="exito">{{mensaje}}</p></div></AdminLayout></template>
<style scoped>.shell{display:grid;gap:20px}.cabecera{display:flex;justify-content:space-between;align-items:center}.cabecera h2{font-size:29px;margin:7px 0}.cabecera p:last-child,.muted{color:#929a90}.columnas{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(290px,.7fr);gap:20px}.columnas aside{display:grid;align-content:start;gap:20px}.repuesto{display:grid;grid-template-columns:2fr .6fr .8fr auto;gap:8px}.repuesto select,.repuesto input{min-width:0}.repuesto button{background:#321819;border:1px solid #5c3535;color:#ffb4ab;border-radius:6px}.agregar{justify-self:start;background:none;border:0}.resumen p,.pago{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #333}.resumen .total{font-size:18px}.resumen .saldo{color:#79dd68;font-size:19px}.pago div{display:flex;flex-direction:column;gap:3px}.pago small{color:#888}.exito{color:#79dd68}.error{color:#ffb4ab}@media(max-width:900px){.columnas{grid-template-columns:1fr}}@media(max-width:600px){.repuesto{grid-template-columns:1fr 1fr}.repuesto select{grid-column:1/-1}}
</style>
